version: '3.7'
services:
  php:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - '../web:/var/www/html'
      - './php_config/custom_php.ini:/usr/local/etc/php/conf.d/custom.ini'
      - './php_config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
      - './php_config/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini'
    ports:
      - '443:443'
      - '80:80'
  db:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - './db_data:/var/lib/mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 12345678
